#!/usr/bin/env python3
"""Plan periodic正文抽检 for the name-hash concept refresh mode.

Name/path metadata is intentionally the daily signal.  This planner is the
small safety net for edits made in place: it schedules a deterministic bucket
of sources and gives Active-concept sources a shorter deadline.  It only
plans work; a Codex runner performs the actual body read and records audit
results later.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence


SCHEMA_VERSION = "concept-content-audit-queue.v1"
NAME_HASH_PREFIX = "namepath-v1:"
LEGACY_NAME_HASH_PREFIX = "sha256:"
NAME_HASH_FORMAT = "namepath-v1"
BUCKET_COUNT = 8
ACTIVE_MAX_AGE_DAYS = 30
NORMAL_MAX_AGE_DAYS = 90


def _read_json(path: Optional[Path], default: Any) -> Any:
    if not path:
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default


def _parse_time(value: Any) -> Optional[datetime]:
    text = str(value or "").strip()
    if not text:
        return None
    try:
        result = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError:
        return None
    return result.replace(tzinfo=result.tzinfo or timezone.utc).astimezone(timezone.utc)


def canonical_name_hash(value: Any) -> str:
    """Normalize legacy name fingerprints for audit comparisons only."""
    text = str(value or "").strip()
    if text.startswith(NAME_HASH_PREFIX):
        return text
    if text.startswith(LEGACY_NAME_HASH_PREFIX):
        return NAME_HASH_PREFIX + text[len(LEGACY_NAME_HASH_PREFIX):]
    return text


def name_hash_equal(left: Any, right: Any) -> bool:
    """Treat old ``sha256:`` and new ``namepath-v1:`` values as equivalent."""
    left_value = canonical_name_hash(left)
    right_value = canonical_name_hash(right)
    return bool(left_value and right_value and left_value == right_value)


def stable_bucket(source_id: str, bucket_count: int = BUCKET_COUNT) -> int:
    if bucket_count <= 0:
        raise ValueError("bucket_count must be positive")
    digest = hashlib.sha256(str(source_id).encode("utf-8")).digest()
    return int.from_bytes(digest[:8], "big") % bucket_count


def _week_bucket(now: datetime, bucket_count: int = BUCKET_COUNT) -> int:
    iso = now.isocalendar()
    return (int(iso.year) * 53 + int(iso.week)) % bucket_count


def _active_by_source(manifest: Mapping[str, Any]) -> Dict[str, List[str]]:
    result: Dict[str, List[str]] = {}
    for row in manifest.get("active_source_checks") or []:
        if not isinstance(row, Mapping):
            continue
        source_uri = str(row.get("source_uri") or "")
        if not source_uri:
            continue
        for source_id in row.get("matched_source_ids") or []:
            result.setdefault(str(source_id), []).append(str(row.get("concept") or ""))
    return {key: sorted({name for name in values if name}) for key, values in result.items()}


def _unmapped_active(manifest: Mapping[str, Any]) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for check in manifest.get("unmapped_active_sources") or []:
        if not isinstance(check, Mapping):
            continue
        uri = str(check.get("source_uri") or "")
        concept = str(check.get("concept") or "")
        if uri:
            rows.append({
                "source_id": f"unmapped:{uri}",
                "source": "unmapped-source",
                "doc_guid": None,
                "path": uri,
                "name": uri.rstrip("/").rsplit("/", 1)[-1],
                "name_hash": None,
                "name_hash_rule": manifest.get("name_hash_rule"),
                "revision_kind": "unknown",
                "heuristic": True,
                "origin": "active_source",
                "metadata_status": "unmapped",
                "active_concepts": [concept] if concept else [],
            })
    return rows


def _rotation_offsets(previous: Mapping[str, Any], bucket_count: int) -> Dict[str, int]:
    """Load the next offset for each bucket, tolerating pre-cursor queues."""
    offsets = {str(bucket): 0 for bucket in range(bucket_count)}
    raw = previous.get("rotation_offsets")
    if isinstance(raw, Mapping):
        for bucket in range(bucket_count):
            value = raw.get(str(bucket), raw.get(bucket, 0))
            try:
                offsets[str(bucket)] = max(0, int(value))
            except (TypeError, ValueError):
                offsets[str(bucket)] = 0
    # A short-lived prototype used one scalar offset.  Keep it readable so a
    # queue generated by that version does not silently restart at zero.
    if isinstance(previous.get("rotation_offset"), (int, float, str)):
        bucket = previous.get("selected_bucket")
        try:
            bucket_key = str(int(bucket))
            if bucket_key in offsets and not isinstance(raw, Mapping):
                offsets[bucket_key] = max(0, int(previous["rotation_offset"]))
        except (TypeError, ValueError):
            pass
    return offsets


def _paged_slice(rows: Sequence[Dict[str, Any]], offset: int, count: int) -> List[Dict[str, Any]]:
    """Take one contiguous page and leave wraparound to the next run.

    Keeping the offset monotonic prevents the final short page of a bucket
    from wrapping back to its first rows in the same run.  Once the offset is
    at least the current candidate count, the next invocation naturally starts
    a new rotation cycle via modulo arithmetic.
    """
    if not rows or count <= 0:
        return []
    start = max(0, int(offset)) % len(rows)
    take = min(int(count), len(rows) - start)
    return list(rows[start : start + take])


def build_audit_queue(
    manifest: Mapping[str, Any],
    previous: Optional[Mapping[str, Any]] = None,
    *,
    now: Optional[datetime] = None,
    limit: int = 800,
    bucket_count: int = BUCKET_COUNT,
) -> Dict[str, Any]:
    now = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    previous = previous if isinstance(previous, Mapping) else {}
    previous_observed = previous.get("observed") if isinstance(previous.get("observed"), Mapping) else {}
    rotation_offsets = _rotation_offsets(previous, bucket_count)
    active_by_source = _active_by_source(manifest)
    documents = [dict(row) for row in manifest.get("documents") or [] if isinstance(row, Mapping)]
    documents.extend(_unmapped_active(manifest))
    current_observed: Dict[str, Dict[str, Any]] = {}
    planned: List[Dict[str, Any]] = []
    for row in documents:
        source_id = str(row.get("source_id") or row.get("path") or "")
        if not source_id:
            continue
        old = previous_observed.get(source_id) if isinstance(previous_observed, Mapping) else {}
        old = old if isinstance(old, Mapping) else {}
        active_concepts = sorted(set(active_by_source.get(source_id, [])) | set(row.get("active_concepts") or []))
        last_audit = str(old.get("last_content_audit_at") or row.get("last_content_audit_at") or "")
        publish_time = str(row.get("publishTime") or row.get("fetched_at") or row.get("updated_at") or "")
        old_name_hash = str(old.get("name_hash") or "")
        current_name_hash = str(row.get("name_hash") or "")
        publish_suspect = bool(
            publish_time and str(old.get("publish_time") or "") and publish_time != str(old.get("publish_time"))
            and current_name_hash and name_hash_equal(current_name_hash, old_name_hash)
        )
        last_dt = _parse_time(last_audit)
        # A missing audit is an initial state, not an overdue audit.  Treating
        # every missing timestamp as due would enqueue the entire inventory on
        # the first run and defeat the eight-week rotation policy.
        has_previous_audit = last_dt is not None
        age_days = (now - last_dt).total_seconds() / 86400 if last_dt else None
        max_age = ACTIVE_MAX_AGE_DAYS if active_concepts else NORMAL_MAX_AGE_DAYS
        due = has_previous_audit and age_days >= max_age
        scheduled = stable_bucket(source_id, bucket_count) == _week_bucket(now, bucket_count)
        initial_active = bool(active_concepts) and not has_previous_audit
        initial_rotation = not active_concepts and not has_previous_audit and scheduled
        reasons: List[str] = []
        if publish_suspect:
            reasons.append("publish_time_changed")
        if initial_active:
            reasons.append("initial_active_audit")
        elif initial_rotation:
            reasons.append("initial_rotation_bucket")
        elif due:
            reasons.append("audit_due")
        elif scheduled:
            reasons.append("rotation_bucket")
        current_observed[source_id] = {
            "name_hash": current_name_hash or None,
            "publish_time": publish_time or None,
            "last_content_audit_at": last_audit or None,
            "active_concepts": active_concepts,
        }
        if not reasons:
            continue
        priority = "active" if active_concepts else "normal"
        planned.append({
            **row,
            "source_id": source_id,
            "active_concepts": active_concepts,
            "bucket": stable_bucket(source_id, bucket_count),
            "priority": priority,
            "reason": reasons[0] if len(reasons) == 1 else "|".join(reasons),
            "last_content_audit_at": last_audit or None,
            "audit_max_age_days": max_age,
            "status": "pending",
        })
    priority_order = {"active": 0, "normal": 1}
    planned.sort(key=lambda row: (
        0 if "publish_time_changed" in str(row.get("reason")) else 1,
        priority_order.get(str(row.get("priority")), 9),
        0 if "audit_due" in str(row.get("reason")) else 1,
        str(row.get("path") or ""),
    ))
    selected_limit = max(0, int(limit))
    selected_bucket = _week_bucket(now, bucket_count)
    selected_bucket_key = str(selected_bucket)
    rotation_offset = rotation_offsets.get(selected_bucket_key, 0)

    # A publish-time suspect, Active source, or age-due item is mandatory.  It
    # must not consume the ordinary rotation cursor, otherwise a noisy source
    # can permanently displace the rest of its bucket.
    mandatory: List[Dict[str, Any]] = []
    rotation_candidates: List[Dict[str, Any]] = []
    for row in planned:
        reason = str(row.get("reason") or "").split("|")
        is_mandatory = (
            row.get("priority") == "active"
            or "publish_time_changed" in reason
            or "audit_due" in reason
        )
        if is_mandatory:
            mandatory.append(row)
        elif row.get("bucket") == selected_bucket and any(
            token in {"rotation_bucket", "initial_rotation_bucket"} for token in reason
        ):
            rotation_candidates.append(row)

    selected_mandatory = mandatory[:selected_limit]
    remaining = max(0, selected_limit - len(selected_mandatory))
    selected_rotation = _paged_slice(rotation_candidates, rotation_offset, remaining)
    selected = selected_mandatory + selected_rotation
    if selected_rotation:
        # Keep an absolute cursor.  The next run wraps only after the current
        # bucket has been fully consumed, so a short final page cannot repeat
        # the first page immediately.
        next_rotation_offset = rotation_offset + len(selected_rotation)
    else:
        next_rotation_offset = max(0, rotation_offset) if rotation_candidates else 0
    rotation_offsets[selected_bucket_key] = next_rotation_offset
    metrics = {
        "document_count": len(documents),
        "planned_count": len(planned),
        "selected_count": len(selected),
        "active_planned_count": sum(1 for row in planned if row.get("priority") == "active"),
        "active_selected_count": sum(1 for row in selected if row.get("priority") == "active"),
        "publish_suspect_count": sum(1 for row in planned if "publish_time_changed" in str(row.get("reason"))),
        "due_count": sum(1 for row in planned if "audit_due" in str(row.get("reason"))),
        "rotation_count": sum(1 for row in planned if "rotation_bucket" in str(row.get("reason"))),
        "initial_active_count": sum(1 for row in planned if "initial_active_audit" in str(row.get("reason"))),
        "initial_rotation_count": sum(1 for row in planned if "initial_rotation_bucket" in str(row.get("reason"))),
        "mandatory_count": len(mandatory),
        "mandatory_selected_count": len(selected_mandatory),
        "rotation_candidate_count": len(rotation_candidates),
        "rotation_selected_count": len(selected_rotation),
        "rotation_offset": rotation_offset,
        "rotation_next_offset": next_rotation_offset,
        "unmapped_active_count": sum(1 for row in selected if row.get("metadata_status") == "unmapped"),
    }
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at": now.replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "revision_mode": "name_hash",
        "name_hash_prefix": NAME_HASH_PREFIX,
        "name_hash_format": NAME_HASH_FORMAT,
        "heuristic": True,
        "bucket_count": bucket_count,
        "selected_bucket": selected_bucket,
        "rotation_offsets": rotation_offsets,
        "policy": {
            "active_max_age_days": ACTIVE_MAX_AGE_DAYS,
            "normal_max_age_days": NORMAL_MAX_AGE_DAYS,
            "rotation_weeks": bucket_count,
        },
        "metrics": metrics,
        "observed": current_observed,
        "items": selected,
    }


def write_json(path: Path, value: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_suffix(path.suffix + ".tmp")
    temp.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    temp.replace(path)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Plan deterministic concept content audits")
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--previous", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--limit", type=int, default=800)
    args = parser.parse_args(argv)
    manifest = _read_json(args.manifest, {})
    if not isinstance(manifest, Mapping):
        parser.error("manifest must be a JSON object")
    previous = _read_json(args.previous, {}) if args.previous else {}
    payload = build_audit_queue(manifest, previous, limit=args.limit)
    write_json(args.output, payload)
    print(json.dumps(payload["metrics"], ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
